### ISSUE TITLE
Add support for double tap drag to zoom

### ISSUE THREAD

**Issue by eveliotc** [lyft/scissors#1]
Currently we use custom touch handling for zooming and snapping, we should use `ScaleGestureDetector` which has out of the box double tap to drag zooming.

[From Gestures](https://www.google.com/design/spec/patterns/gestures.html#gestures-touch-activities)

![double-tap-drag](https://cloud.githubusercontent.com/assets/400641/11257234/30908a8a-8e05-11e5-8212-af9efb806efa.png)

**Comment by johnhiott** [comment]
If no one is currently tackling this, I will give it a go.
