### ISSUE TITLE
How to check if image has been cropped/modified ?

### ISSUE THREAD

**Issue by rishirajput** [lyft/scissors#103]
Hi,
Unable to check whether the image has been cropped or not.
Both the cropped and uncropped image bitmaps have same widht and height (as viewport size is fixed on crop page) but they differ in pixels.

Tried using bitmap sameAs() to compare crop() (cropped bitmap returned) and getImageBitmap() (image source bitmap),
even though I don't perform any cropping on the image, cropped and source image still differ in pixels when we press
Bitmap sameAs() returns false when comparing crop() with getImageBitmap()

**Comment by mikecutalo** [comment]
Thank you for you contribution to this repository.

Closing this Issue as this repository is being archived.
