### ISSUE TITLE
Image does not load + selecting an image loop

### ISSUE THREAD

**Issue by rohanmahale** [lyft/scissors#12]
I tested my app on a Sony Ericsson Xperia S. It is using scissors to select images to crop before adding them. 
I have used the selection as shown in the sample app.

```
cropView.extensions().pickUsing (this,REQ_CODE)
```

This works perfectly well on other devices that I have tested it on - Xiaomi, Samsung s3, Galaxy S4.
However on the   Sony Ericsson Xperia S, when I select an image to crop, many times the cropView does not load the image instead the selection prompt pops up again. Is this related to the other load issue?

**Comment by eveliotc** [comment]
@rohanmahale first part (image not loading) might be related to #6 so please try snapshot and let me know if that fixes that part, as per  

> the selection prompt pops up again

It might be due multiple `pickUsing` calls, can you please confirm `pickUsing` is only called once?

**Comment by rohanmahale** [comment]
@eveliotc  pickUsing is called only once.

**Comment by rohanmahale** [comment]
The load issue is fixed. The issue of the recurring popup still exists. I used a workaround and stopped using pickUsing(). I passed the file path(converting the Uri) via an extra to my cropping activity and directly load this using load(). Should I close this?

**Comment by dschaller** [comment]
Thank you for you contribution to this repository.

Closing this contribution as this repository is being archived.
