### ISSUE TITLE
Guidelines over the image

### ISSUE THREAD

**Issue by Odaym** [lyft/scissors#13]
It would be nice if you could add some guidelines over the image or anything that would offer the familiar look of an image-cropping screen so that the user will instantly understand that this is where cropping happens, not just to read the activity title to know they now can crop

Does that make sense?

**Comment by eveliotc** [comment]
@Odaym do you mean having a grid like the camera?

![device-2015-11-30-110835](https://cloud.githubusercontent.com/assets/400641/11481555/f05d5d42-9752-11e5-990f-f3a883346998.png)

**Comment by Odaym** [comment]
Yep, that's the one! It would show something familiar so that the user could instantly recognize the purpose maybe

**Comment by eveliotc** [comment]
@Odaym cool, @maksim88 sent #15 which attempts to solve a similar problem, we don't have such requirement however I'll try to aggregate both requirements and send a PR later this week

**Comment by cxzhang2** [comment]
@eveliotc, is this feature still being considered?

**Comment by tildedave** [comment]
Hi there, we are cleaning up the repo.  Sorry for the late response but we don't plan to support this feature at this point.
