### ISSUE TITLE
cannot set width height ratio dynamically from code

### ISSUE THREAD

**Issue by qinjunli** [lyft/scissors#20]
I want to customize the crop ratio dynamically from code, but no support currently..

**Comment by hlau-lyft** [comment]
Hi Junli

We didn't have the dynamic crop ratio requirement at that time but I think it's useful to have this feature. I will add this support and let you know when it's ready. 

Regards

Helen

**Comment by qinjunli** [comment]
Looking forward to .. ^_^

**Comment by timkoers** [comment]
When do you expect to have it ready? I kind of need it :-)

If you can't figure it out, I might just be in the mood to make one :+1: 

Just let me know.

**Comment by hlau-lyft** [comment]
Hi Timkoers,

This request is not on top of our priority list.  Please go ahead.

Thanks,

Helen

## 

_Helen Lau_
Android Engineer
650.302.8957 <+16503028957>
[image: Lyft] http://www.lyft.com/

**Comment by eveliotc** [comment]
Merging this into #26
