### ISSUE TITLE
It doesn't work when trying to pick picture from camera.

### ISSUE THREAD

**Issue by Warnier-zhang** [lyft/scissors#30]
Here is the related code:

 private void loadImageFromCamera() {
        Intent intent = new Intent(MediaStore.ACTION_IMAGE_CAPTURE);
        Uri imageUri = Uri.fromFile(createExternalCacheFile("avatar_camera.png"));
        intent.putExtra(MediaStore.EXTRA_OUTPUT, imageUri);
        startActivityForResult(intent, PICK_IMAGE_FROM_CAMERA);
    }

protected void onActivityResult(int requestCode, int resultCode, Intent data) {
        super.onActivityResult(requestCode, resultCode, data);
        if (requestCode == PICK_IMAGE_FROM_GALLERY && resultCode == RESULT_OK) {
            Uri imageUri = data.getData();
            mCropView.extensions().load(imageUri);
        }
        if (requestCode == PICK_IMAGE_FROM_CAMERA && requestCode == RESULT_OK) {
            Bitmap bitmap = null;
            try {
                bitmap = BitmapFactory.decodeStream(new FileInputStream(createExternalCacheFile("avatar_camera.png")));
                mCropView.setImageBitmap(bitmap);
            } catch (FileNotFoundException e) {
                e.printStackTrace();
            }
        }
    }

CropView doesn't show the bitmap.

**Comment by rharter** [comment]
If you debug is the bitmap actually getting loaded?

Also, scissors takes care of loading images from Uris for you, so why load it yourself and not just do `mCropView.extension().load(Uri.fromFile(createExternalCacheFile("avatar_camera.png")))`?

**Comment by Warnier-zhang** [comment]
I have also tried the code.
mCropView.extension().load(Uri.fromFile(createExternalCacheFile("avatar_camera.png")))

The CropView doesn't show the bitmap taken from the camera, either.

**Comment by Warnier-zhang** [comment]
I fixed the problem.

I find that the method "CropView.extensions().crop().quality(87).format(PNG).into(file)" seems to need a period of time to store the image file. Does it?

**Comment by rharter** [comment]
It's an asynchronous request, so it will take some time. Try running the sample.  Does that give you the same result you're looking for?  If so, then you can model your code directly off that.
