### ISSUE TITLE
How can I get coordinates?

### ISSUE THREAD

**Issue by virengujariya** [lyft/scissors#32]
I want cropped coordinates on original image. Is it possible with this library?

**Comment by eveliotc** [comment]
@virengujariya there is no API for this as of now, adding `help wanted` to see if someone is interested on contributing this

**Comment by konecnyna** [comment]
There is another [request](https://github.com/lyft/scissors/issues/33) for this feature. Would be really nice to have

**Comment by tildedave** [comment]
#74 was merged, let me know if this doesn't solve your issue.
