### ISSUE TITLE
Image loaded from Galaxy S6 rotated with 90 degrees 

### ISSUE THREAD

**Issue by davidbeloo** [lyft/scissors#34]
I tried it on Galaxy S6 running 5.1.1
And if I try to load an image, the image is rotated in 90 degrees even before cropping.

**Comment by rharter** [comment]
@davidbeloo How are you loading the image?  Depending on your image loader, it may not be reading the EXIF data from the jpeg.  Try the Glide loader and see if that helps (Glide will read the EXIF rotation info, Picasso won't)

**Comment by davidbeloo** [comment]
@rharter I just used your sample, I didn't change a single line.
Should I download Glide to my project, or  you have some build in way to use Glide?

**Comment by eveliotc** [comment]
@davidbeloo sample uses Picasso by default, can you provide image so we can debug? either here or email at `evelio@lyft.com`

**Comment by davidbeloo** [comment]
Ok, Thanks @rharter and @eveliotc 
It's working with Glide as below:

In the onActivityResult of the `MainActivity` in the sample
I comment out:
`//cropView.extensions().load(galleryPictureUri)`
And use Glide as you said: `Glide.with(this).load(galleryPictureUri).diskCacheStrategy(DiskCacheStrategy.NONE).skipMemoryCache(true).into(cropView);`

And of course uncomment  `compile 'com.github.bumptech.glide:glide:3.6.1'` in gradle file

`

**Comment by rharter** [comment]
@eveliotc Just a note, I've run into this with certain Samsung phones, and in the wild on others.  Not specifically with Scissors, it's just that they write the image bytes in a fixed orientation and use the EXIF orientation to specify the actual rotation.  Glide reads EXIF orientation from jpegs, Picasso does not.  That is noted here: https://github.com/square/picasso/issues/691#issuecomment-127401492

**Comment by rharter** [comment]
@davidbeloo Just a note about loading the image with glide, there is a glide image loader in Scissors that will allow you to load images with the same syntax as you would with Picasso.  If you simply add the glide dependency and remove the Picasso dependency, it will automatically choose the correct one, otherwise you can manually specify like this:

``` java
mCropView.extensions()
  .using(GlideBitmapLoader.createUsing(mCropView))
  .load(imageUri);
```

**Comment by davidbeloo** [comment]
@rharter Thanks a lot for your help! :)

**Comment by eveliotc** [comment]
@rharter correct, Picasso only relies on MediaStore to provide exif rotation, if such information is missing then we end up with issues like this, another reason to support #9
