### ISSUE TITLE
CONTRIBUTING.md has a broken link to the java code styles

### ISSUE THREAD

**Issue by nathanjones** [lyft/scissors#36]
My guess is that your `java-code-styles` repo is private, but regardless this is a broken link:

https://github.com/lyft/java-code-styles

I would love to start contributing and wanted to respect existing convention, but the code style isn't publicly available.

**Comment by eveliotc** [comment]
It got renamed and made private recently, please use whatever codestyle for now, will close this once it's resolved.

**Comment by dschaller** [comment]
Thank you for you contribution to this repository.

Closing this contribution as this repository is being archived.
