### ISSUE TITLE
W/EGL_emulation: eglSurfaceAttrib not implemented,  W/OpenGLRenderer: Failed to set EGL_SWAP_BEHAVIOR on surface 0xe0162fc0, error=EGL_SUCCESS

### ISSUE THREAD

**Issue by thomasdola** [lyft/scissors#38]
`W/OpenGLRenderer: Failed to set EGL_SWAP_BEHAVIOR on surface 0xe0162fc0, error=EGL_SUCCESS`
Getting the above error anytime i try loading the image into the cropView.
any help on that please?

**Comment by eveliotc** [comment]
@thomasdola can you please attach full log? also image if you have it, few more questions: device? android version? bitmap loader?

**Comment by thomasdola** [comment]
`03-16 11:52:02.811 3527-3576/primr.apps.eurakacachet.com.primr W/EGL_emulation: eglSurfaceAttrib not implemented
03-16 11:52:02.811 3527-3576/primr.apps.eurakacachet.com.primr W/OpenGLRenderer: Failed to set EGL_SWAP_BEHAVIOR on surface 0xdfef51a0, error=EGL_SUCCESS
03-16 11:52:09.751 3527-3527/primr.apps.eurakacachet.com.primr I/BranchSDK: Branch Warning: You are using your test app's Branch Key. Remember to change it to live Branch Key during deployment.
03-16 11:52:09.780 3527-3576/primr.apps.eurakacachet.com.primr W/EGL_emulation: eglSurfaceAttrib not implemented
03-16 11:52:09.780 3527-3576/primr.apps.eurakacachet.com.primr W/OpenGLRenderer: Failed to set EGL_SWAP_BEHAVIOR on surface 0xdfef51a0, error=EGL_SUCCESS
03-16 11:52:09.796 3527-3527/primr.apps.eurakacachet.com.primr W/ViewRootImpl: Dropping event due to no window focus: KeyEvent { action=ACTION_DOWN, keyCode=KEYCODE_ALT_RIGHT, scanCode=100, metaState=META_ALT_ON|META_ALT_RIGHT_ON, flags=0x8, repeatCount=12142, eventTime=654913, downTime=31233, deviceId=1, source=0x301 }
`

**Comment by thomasdola** [comment]
it is not really an error because my app is still functioning, just that i cannot load the load the image to even say that am cropping it.
i get the warning after selecting the image that is to be cropped.
worth mentioning that it used to work before (pretty well), and all of a sudden stopped..
thanks...

**Comment by eveliotc** [comment]
@thomasdola can you please provide the other info? I would like to take a look this after droidcon

**Comment by thomasdola** [comment]
there is no any other info, the rest is just my own logging...

**Comment by bcahlit** [comment]
I encountered this problem in the pull in the content provider.
But I made a mistake to pull. No permission to declare the content provider needed

**Comment by dschaller** [comment]
Thank you for you contribution to this repository.

Closing this contribution as this repository is being archived.
