### ISSUE TITLE
cropviewViewportOverlayPadding

### ISSUE THREAD

**Issue by denghewenai** [lyft/scissors#40]
No resource identifier found for attribute 'cropviewViewportOverlayPadding' in package .Why use android studio  to add dependency can not find this attribute.

**Comment by denghewenai** [comment]
![qq 20160412175328](https://cloud.githubusercontent.com/assets/13479936/14456442/846a4db8-00d7-11e6-9b85-b48b63915c40.png)Your github codes seem no this line.

**Comment by eveliotc** [comment]
@denghewenai can you please elaborate?

**Comment by denghewenai** [comment]
Sorry, my english is not good.I Add the dependence on the library in Androidstudio,but can't use the attribute 'cropviewViewportOverlayPadding' .It throws an exception that 'No resource identifier found for attribute 'cropviewViewportOverlayPadding' in package .'.I go to look over the class 'CropViewConfig',but I didn't find the lines of code on screenshot.

**Comment by eveliotc** [comment]
No worries, non-native speaker here as well, the reason why isn't resolved on Android Studio is because it hasn't been deployed, Thanks @denghewenai will get to release it soon

**Comment by denghewenai** [comment]
Thanks for your reply.

**Comment by eveliotc** [comment]
Just released this on `1.1.0` please update. thanks!

**Comment by denghewenai** [comment]
OK,I have updated it.My problem has been solved.Thank you.
