### ISSUE TITLE
pickUsing method does not support fragments

### ISSUE THREAD

**Issue by mattkrebs** [lyft/scissors#41]
when calling `cropView.extensions()
                .pickUsing(this, RequestCodes.PICK_IMAGE_FROM_GALLERY);` from with in a fragment returns the result to the parent activity and not back to the fragments `onActivityResult`  Is there a work around or is this something that can be added.   Thanks for the library, loving it so far.

**Comment by eveliotc** [comment]
Thanks @mattkrebs we use [scoop](https://github.com/lyft/scoop) that's why we missed fragments ;) Adding support for fragments shouldn't be complicated, will add it for next release.

**Comment by eveliotc** [comment]
#43 Added support for framework Fragments, if you are using support-v4 Fragments, consider using something similar to this in your code base

https://github.com/lyft/scissors/pull/43/files#diff-048c760754d3c26822798af85fdb8d6aR39

I did not want to add a dependency on support-v4 at the moment, hoping to refactor extensions as separate artifacts in the future.
