### ISSUE TITLE
does scissors require READ_EXTERNAL_STORAGE permission?

### ISSUE THREAD

**Issue by luoapril** [lyft/scissors#50]
I've been seeing some crashes come in with the following error message:

`Permission Denial: reading com.android.providers.media.MediaProvider uri content://media/external/images/media/1037 from pid=23237, uid=10079 requires android.permission.READ_EXTERNAL_STORAGE, or grantUriPermission()`

This happens after I call `cropView.extensions().pickUsing(...)`, but I can't seem to reproduce it on any of my devices.

Thanks in advance!

**Comment by eveliotc** [comment]
That might be the case we don't support runtime permissions at the moment.
