### ISSUE TITLE
Getting position and Current scale of the image

### ISSUE THREAD

**Issue by LonerganOnline** [lyft/scissors#55]
Can the Crop view be used to re position an image in a container. the image is bigger than the CropView and i need to chose which area is visible trough the view port.  to do this i would need to get the x and y position of the image in relation tho the cropView. I am using this library for cropping image in another section of my app and would like to reuse it for this function as it handles the dragging and scaling for me but after playing around with it i could not get ant information on the positioning of the image. is this supported or do i need to look else where.

**Comment by eveliotc** [comment]
This is not supported at the moment.
