### ISSUE TITLE
reset transform

### ISSUE THREAD

**Issue by jachenry** [lyft/scissors#58]
We have a flow requiring multiple images to be selected and cropped. The issue is the CropView's transform sticks around even after loading a new image. Is there a way to reset the transform applied to the CropView before we load the next image?

**Comment by eveliotc** [comment]
@jachenry Please considering loading the images at your convenience and then setting it on the view e.g. `cropView.setImageBitmap(Bitmap);`

**Comment by jachenry** [comment]
I forked the repo and recreate the touch manager anytime a new bitmap is set. Thank you for creating this project and the response to my question.

https://github.com/jachenry/scissors/commit/3a06dbd87e883f787614ff4d1f6492951f34ce55
