### ISSUE TITLE
White place if crop is max to right

### ISSUE THREAD

**Issue by stefi92** [lyft/scissors#60]
Hi, I have an issue, when I move image to maximum right and then crop him, there's a white place. Can you help me please?

**Comment by stefi92** [comment]
the way how I cropp the image: 
`FileOutputStream out = null;
        try {
            out = new FileOutputStream("storage/emulated/0/Pictures/be_reporter_cropp_temp.jpg");
            cropImageView.crop().compress(Bitmap.CompressFormat.PNG, 87, out);
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            if (out != null) {
                out.close();
                Intent result = new Intent();
                setResult(RESULT_OK, result);
                finish();
            }
        }`

**Comment by tildedave** [comment]
Hi there, closing this as it's pretty old.  Feel free to reopen if you're still having this issue.
