### ISSUE TITLE
Want to t support more CropMode?

### ISSUE THREAD

**Issue by NicodeLee** [lyft/scissors#7]
Such as:circle,4_3 , 3_4 , 16_9.

**Comment by eveliotc** [comment]
Any ratio is already supported, all you have to do is specify `cropviewViewportHeightRatio` in your layout as follows:

##### 16_9 = 9/16 = `cropviewViewportHeightRatio="0.5625"`

<img alt="16_9" width="300px" src="https://cloud.githubusercontent.com/assets/400641/11412336/739d74c4-9390-11e5-8c68-aeecbbc7cd14.png" />

##### 4_3 = 3/4 = `cropviewViewportHeightRatio="0.75"`

<img alt="4_3" width="300px" src="https://cloud.githubusercontent.com/assets/400641/11412280/ffc1eab2-938f-11e5-869a-4c4b1aebf730.png" />

##### 3_4 = 4/3 = `cropviewViewportHeightRatio="1.33"`

<img alt="3_4" width="300px" src="https://cloud.githubusercontent.com/assets/400641/11412320/50e01a90-9390-11e5-8af3-0bc31c3dd2eb.png" />

I guess we could formalize most common ratios as enum, circle could be also supported.

**Comment by lexer** [comment]
@NicodeLee We don't have plans for circle cropping. It's usually better to always to do square cropping and then do circle transformation only when you display image in ui. (Primary reason is that in different parts of the app you could display same image in square and circle format)

If you want to give user feeling that he crops circle just use circle transparent overlay on the top of crop view.

**Comment by NicodeLee** [comment]
@lexer @eveliotc Thanks for your reply.
