### ISSUE TITLE
Can I use scissors library to crop an image taken with my camera? <question>

### ISSUE THREAD

**Issue by vjgonzalez** [lyft/scissors#72]
First of all, this is a question, but sorry, I don't know how to add the label to it.

Hi, from what I've seen, this library is useful to select an image from the fallery and then crop it. Is there a way to open the device's camera, take a picture, and then crop it? If so, can you tell me how?

Thanks!

**Comment by jaadchacra** [comment]
How is this closed? Can you post your solution please?
