### ISSUE TITLE
Crop to File, cannot access CropViewExtensions

### ISSUE THREAD

**Issue by mrgcl** [lyft/scissors#85]
Trying to crop into file using scissors 1.1.1 and i get the following error when compiling 

> Error:(49, 22) Cannot access 'CropViewExtensions': it is public/*package*/ in 'com.lyft.android.scissors'

The code in question is basically the same as the example provided.
```
mCropView.extensions()
                    .crop()
                    .quality(87)
                    .format(PNG)
                    .into(file)
```

**Comment by BraisGabin** [comment]
Are you probably using kotlin? You must upgrade to kotlin 1.1+: https://youtrack.jetbrains.com/issue/KT-11398

**Comment by EricKuck** [comment]
This issue still exists in the latest version of Kotlin (1.2.21). Why is CropViewExtensions package-private in the first place?

Edit: I see it's fixed in 2.0 if you're willing to build it yourself. Even the snapshot repo hasn't been updated since 2016. Hopefully helpful for anyone else who comes across this.

**Comment by mayojava** [comment]
@EricKuck were you able to solve this problem? I am currently facing this same issue.

**Comment by EricKuck** [comment]
I found a better supported lib and switched to that. If you're really set on Scissors, you can build it yourself or use something like jitpack to grab it from the repo.

**Comment by dri94** [comment]
@EricKuck what lib did you switch to?

**Comment by mikecutalo** [comment]
Thank you for you contribution to this repository.

Closing this Issue as this repository is being archived.
