### ISSUE TITLE
Can I get the cropped offsets?

### ISSUE THREAD

**Issue by sujan219** [lyft/scissors#88]
Hi, is there any way I could get the cropped offset (left and top)?

**Comment by spadafiva** [comment]
@sujan219 I'm looking to do this too.  Did you end up finding a way to do so?

**Comment by sujan219** [comment]
Hi @spadafiva,
I ended up using cropView.getTransformation().getCrop() method.

**Comment by spadafiva** [comment]
Thanks @sujan219, I'll take a look at that

**Comment by spadafiva** [comment]
@sujan219 I've been working on and off for this and it looks like I can use (kotlin) `cropImageView.transformMatrix`, but I can't find the `transformation.crop` that you're talking about.  

How would I go about converting a matrix to get the offset?

**Comment by mikecutalo** [comment]
Thank you for you contribution to this repository.

Closing this Issue as this repository is being archived.
