### ISSUE TITLE
Scissors 2 is not available on maven

### ISSUE THREAD

**Issue by tinder-davidknight** [lyft/scissors#90]
can't import scissors 2 using gradle with `com.lyft:scissors:2.0.0-SNAPSHOT`

**Comment by carlosmuvi** [comment]
Hi @tinder-davidknight !

Until Lyft publishes it, I forked it and you can add the dependency from JitPack:

```
allprojects {
	repositories {
		...
		maven { url 'https://jitpack.io' }
	}
}
```


```
dependencies {
    implementation 'com.github.carlosmuvi:scissors:2.0.0'
}
```
