### ISSUE TITLE
Scissors 2 not published, support for RxJava2

### ISSUE THREAD

**Issue by udaysrinath** [lyft/scissors#97]
- The scissors library version needs to be bumped to 2.0, long due.
- RxJava2 support needs to be added else this block of code in sample https://github.com/lyft/scissors/blob/master/scissors-sample/src/main/java/com/lyft/android/scissorssample/MainActivity.java#L114-L128 does not work. Converting ```Observable.from(..) ``` to ```Observable.fromFuture(..)``` does not seem to function properly.

**Comment by mikecutalo** [comment]
Thank you for you contribution to this repository.

Closing this Issue as this repository is being archived.
